apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: 834725375088.dkr.ecr.us-east-1.amazonaws.com/user:8.0.0
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: user-configmap

--- 

apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  selector:
   app: user
  ports:
    - protocol: TCP
      port: 8080              # Port number of the service that it has to listen on 
      targetPort: 8080        # Port number of the container that it has to forward to

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
data:
  MONGO_URL: "mongodb://admin1:roboshop1@robot-dev-docdb.cluster-ciqb6xvrbz0q.us-east-1.docdb.amazonaws.com:27017/user?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"  
  REDIS_HOST: "robot-dev-redis.ij0ide.0001.use1.cache.amazonaws.com"

--- 

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75